extends Node

# IP Addresses

const LOBBY_MANAGER_NORTH_AMERICA_IPV4 : String = LOCALHOST_IPV4


const LOCALHOST_IPV4 : String = "127.0.0.1"
const LOCALHOST_IPV6 : String = "::1"

# Ports

const LOBBY_MANAGER_TCP_PORT : int = 5378
const LOBBY_MANAGER_UDP_PORT : int = 5379
const LOBBY_MANAGER_ORDERED_UDP_PORT  : int = 5380

const RELAY_MANAGER_TCP_PORT : int = 5378
const RELAY_MANAGER_UDP_PORT : int = 5379
const RELAY_MANAGER_ORDERED_UDP_PORT  : int = 5380
